export const initialRiskAlerts = [
  {
    id: "RSK-9281",
    merchant: "Flash Deals Nusantara",
    signal: "Rp50.000.000 GMV dalam 58 menit pertama",
    severity: "Critical",
    score: 96,
    type: "Velocity anomaly",
    evidence: [
      "632 QRIS intents dari 14 device",
      "Median basket Rp79.114",
      "91% buyer baru dari satu /24 subnet",
    ],
    action: "Payout ditahan otomatis; checkout tetap read-only",
    status: "Open",
  },
  {
    id: "RSK-9278",
    merchant: "Budi Design Vault",
    signal: "Nama rekening payout berbeda dengan identitas KYC",
    severity: "High",
    score: 88,
    type: "Bank-name mismatch",
    evidence: [
      "KYC: BUDI SETIAWAN",
      "Rekening BCA: BUDI SANTOSO",
      "Similarity score hanya 0,61",
    ],
    action: "Withdrawal diblokir; reverifikasi bank diminta",
    status: "Open",
  },
  {
    id: "RSK-9269",
    merchant: "Prompt Factory ID",
    signal: "18 akun buyer memakai fingerprint perangkat yang sama",
    severity: "High",
    score: 82,
    type: "Device reuse",
    evidence: [
      "18 email unik",
      "Satu canvas fingerprint",
      "Kupon yang sama dipakai berulang",
    ],
    action: "Payout ditahan sementara",
    status: "Investigating",
  },
  {
    id: "RSK-9251",
    merchant: "NotionKita",
    signal: "Pola pembayaran sirkular antar akun terhubung",
    severity: "Medium",
    score: 69,
    type: "Circular payments",
    evidence: [
      "4 merchant berbagi IP admin",
      "Email beririsan",
      "Refund ratio 17,2%",
    ],
    action: "Enhanced monitoring selama 72 jam",
    status: "Monitoring",
  },
  {
    id: "RSK-9240",
    merchant: "Digital Supply ID",
    signal: "Spike refund 12% dalam 6 jam",
    severity: "Medium",
    score: 64,
    type: "Refund spike",
    evidence: [
      "18 refund requests",
      "Same product SKU cluster",
      "Buyer emails share provider domain",
    ],
    action: "Manual review queue",
    status: "Open",
  },
  {
    id: "RSK-9232",
    merchant: "Asep AI Tools",
    signal: "Checkout bot fingerprint score tinggi",
    severity: "High",
    score: 79,
    type: "Bot traffic",
    evidence: [
      "Headless browser signals",
      "Uniform user-agent",
      "Low dwell time",
    ],
    action: "Captcha challenge enabled",
    status: "Investigating",
  },
];

export type RiskAlert = (typeof initialRiskAlerts)[number];
