export const merchants = [
  {
    id: "str_01H8A2",
    name: "Asep AI Tools",
    owner: "Asep Kurnia",
    email: "asep@ai.tools",
    volume: 24860000,
    orders: 482,
    risk: "Low",
    status: "Active",
    joined: "18 Mar 2026",
  },
  {
    id: "str_01H8B7",
    name: "DesignKit Studio",
    owner: "Alya Rahman",
    email: "alya@designkit.id",
    volume: 18740000,
    orders: 319,
    risk: "Low",
    status: "Active",
    joined: "2 Apr 2026",
  },
  {
    id: "str_01H8D1",
    name: "Kelas Growth ID",
    owner: "Bima Arya",
    email: "bima@growth.id",
    volume: 12480000,
    orders: 176,
    risk: "Review",
    status: "Restricted",
    joined: "14 May 2026",
  },
  {
    id: "str_01H8F4",
    name: "Preset Nusantara",
    owner: "Rani Setia",
    email: "rani@preset.id",
    volume: 8920000,
    orders: 265,
    risk: "Low",
    status: "Active",
    joined: "29 May 2026",
  },
  {
    id: "str_01H8G9",
    name: "Crypto Signals Pro",
    owner: "Gilang Pratama",
    email: "gilang@signals.id",
    volume: 6310000,
    orders: 88,
    risk: "High",
    status: "Suspended",
    joined: "8 Jun 2026",
  },
  {
    id: "str_01H8H2",
    name: "Notion Desk ID",
    owner: "Maya Kusuma",
    email: "maya@notiondesk.id",
    volume: 5420000,
    orders: 141,
    risk: "Low",
    status: "Active",
    joined: "12 Jun 2026",
  },
  {
    id: "str_01H8J5",
    name: "Prompt Lab Jakarta",
    owner: "Dimas Wira",
    email: "dimas@promptlab.id",
    volume: 4780000,
    orders: 97,
    risk: "Review",
    status: "Active",
    joined: "18 Jun 2026",
  },
  {
    id: "str_01H8K1",
    name: "UI Pack House",
    owner: "Sinta Dewi",
    email: "sinta@uipack.id",
    volume: 3920000,
    orders: 84,
    risk: "Low",
    status: "Active",
    joined: "22 Jun 2026",
  },
  {
    id: "str_01H8L8",
    name: "Automation Club",
    owner: "Raka Firmansyah",
    email: "raka@automation.club",
    volume: 3110000,
    orders: 62,
    risk: "Review",
    status: "Restricted",
    joined: "28 Jun 2026",
  },
  {
    id: "str_01H8M3",
    name: "Copycraft Studio",
    owner: "Nabila Zahra",
    email: "nabila@copycraft.id",
    volume: 2870000,
    orders: 71,
    risk: "Low",
    status: "Active",
    joined: "1 Jul 2026",
  },
  {
    id: "str_01H8N6",
    name: "Edu Course Hub",
    owner: "Taufik Hidayat",
    email: "taufik@educourse.id",
    volume: 2540000,
    orders: 55,
    risk: "High",
    status: "Suspended",
    joined: "4 Jul 2026",
  },
  {
    id: "str_01H8P0",
    name: "Figma Daily",
    owner: "Kevin Adrian",
    email: "kevin@figmadaily.id",
    volume: 2210000,
    orders: 49,
    risk: "Low",
    status: "Active",
    joined: "7 Jul 2026",
  },
];

export const adminOrders = [
  {
    id: "FRS-240712-1842",
    store: "Asep AI Tools",
    customer: "Nadia Putri",
    product: "AI Prompt Pack",
    gross: 79000,
    fee: 3070,
    status: "Paid",
    payment: "QRIS",
    created: "12 Jul, 14:32",
  },
  {
    id: "FRS-240712-1839",
    store: "Asep AI Tools",
    customer: "Rizky Hidayat",
    product: "n8n Automation Pack",
    gross: 149000,
    fee: 5170,
    status: "Paid",
    payment: "QRIS",
    created: "12 Jul, 14:24",
  },
  {
    id: "FRS-240712-1834",
    store: "DesignKit Studio",
    customer: "Dimas Ardi",
    product: "Landing Page Kit",
    gross: 189000,
    fee: 6370,
    status: "Pending",
    payment: "QRIS",
    created: "12 Jul, 14:11",
  },
  {
    id: "FRS-240712-1821",
    store: "Kelas Growth ID",
    customer: "Citra Ayu",
    product: "Growth Playbook",
    gross: 299000,
    fee: 9670,
    status: "Paid",
    payment: "QRIS",
    created: "12 Jul, 13:58",
  },
  {
    id: "FRS-240712-1816",
    store: "Preset Nusantara",
    customer: "Reza Akbar",
    product: "Bali Preset Pack",
    gross: 99000,
    fee: 3670,
    status: "Failed",
    payment: "QRIS",
    created: "12 Jul, 13:42",
  },
  {
    id: "FRS-240712-1808",
    store: "Asep AI Tools",
    customer: "Salsa Nabila",
    product: "AI Prompt Pack",
    gross: 79000,
    fee: 3070,
    status: "Paid",
    payment: "QRIS",
    created: "12 Jul, 13:20",
  },
  {
    id: "FRS-240712-1801",
    store: "DesignKit Studio",
    customer: "Fajar Nugroho",
    product: "Brand System Kit",
    gross: 249000,
    fee: 8170,
    status: "Paid",
    payment: "QRIS",
    created: "12 Jul, 12:58",
  },
  {
    id: "FRS-240712-1755",
    store: "Kelas Growth ID",
    customer: "Intan Maharani",
    product: "Ads Masterclass",
    gross: 449000,
    fee: 14170,
    status: "Pending",
    payment: "QRIS",
    created: "12 Jul, 12:31",
  },
  {
    id: "FRS-240712-1742",
    store: "Notion Desk ID",
    customer: "Yoga Pratama",
    product: "Ops Workspace",
    gross: 129000,
    fee: 4570,
    status: "Paid",
    payment: "QRIS",
    created: "12 Jul, 12:04",
  },
  {
    id: "FRS-240712-1730",
    store: "Prompt Lab Jakarta",
    customer: "Laras Wulandari",
    product: "Prompt OS",
    gross: 159000,
    fee: 5470,
    status: "Paid",
    payment: "QRIS",
    created: "12 Jul, 11:42",
  },
  {
    id: "FRS-240712-1718",
    store: "UI Pack House",
    customer: "Hendra Wijaya",
    product: "Dashboard UI Kit",
    gross: 219000,
    fee: 7270,
    status: "Failed",
    payment: "QRIS",
    created: "12 Jul, 11:18",
  },
  {
    id: "FRS-240712-1704",
    store: "Automation Club",
    customer: "Putri Andini",
    product: "n8n Starter Bundle",
    gross: 179000,
    fee: 6070,
    status: "Paid",
    payment: "QRIS",
    created: "12 Jul, 10:55",
  },
  {
    id: "FRS-240712-1651",
    store: "Copycraft Studio",
    customer: "Bayu Santoso",
    product: "Sales Page Scripts",
    gross: 89000,
    fee: 3370,
    status: "Pending",
    payment: "QRIS",
    created: "12 Jul, 10:22",
  },
];

export const paymentIntents = [
  {
    id: "qris_2Yc91p",
    provider: "Duitku",
    merchant: "Asep AI Tools",
    amount: 79000,
    providerRef: "DKT-9821041",
    status: "Paid",
    latency: "1.2s",
    created: "14:32:08",
  },
  {
    id: "qris_2Yc88a",
    provider: "Duitku",
    merchant: "DesignKit Studio",
    amount: 189000,
    providerRef: "DKT-9821038",
    status: "Pending",
    latency: "842ms",
    created: "14:29:16",
  },
  {
    id: "qris_2Yc74x",
    provider: "Mock",
    merchant: "Kelas Growth ID",
    amount: 299000,
    providerRef: "MOCK-99182",
    status: "Paid",
    latency: "94ms",
    created: "14:21:02",
  },
  {
    id: "qris_2Yc66m",
    provider: "Duitku",
    merchant: "Preset Nusantara",
    amount: 99000,
    providerRef: "DKT-9821011",
    status: "Failed",
    latency: "3.8s",
    created: "14:14:39",
  },
];

export const withdrawalReviews = [
  {
    id: "WD-120724-0092",
    merchant: "Asep AI Tools",
    owner: "Asep Kurnia",
    amount: 12000000,
    bank: "BCA • 4821",
    account: "ASEP KURNIA",
    risk: "Low",
    status: "Pending",
    requested: "12 Jul, 14:06",
  },
  {
    id: "WD-120724-0091",
    merchant: "DesignKit Studio",
    owner: "Alya Rahman",
    amount: 18500000,
    bank: "Mandiri • 1078",
    account: "ALYA RAHMAN",
    risk: "Low",
    status: "Processing",
    requested: "12 Jul, 13:20",
  },
  {
    id: "WD-120724-0088",
    merchant: "Kelas Growth ID",
    owner: "Bima Arya",
    amount: 25000000,
    bank: "BNI • 9034",
    account: "BIMA ARYA",
    risk: "Review",
    status: "On hold",
    requested: "12 Jul, 11:42",
  },
  {
    id: "WD-110724-0082",
    merchant: "Preset Nusantara",
    owner: "Rani Setia",
    amount: 7000000,
    bank: "BCA • 2281",
    account: "RANI SETIA",
    risk: "Low",
    status: "Completed",
    requested: "11 Jul, 09:10",
  },
];

export const riskCases = [
  {
    id: "RSK-4821",
    subject: "Unusual sales velocity",
    merchant: "Kelas Growth ID",
    score: 84,
    severity: "High",
    owner: "Unassigned",
    age: "18m",
  },
  {
    id: "RSK-4818",
    subject: "Repeated failed QRIS attempts",
    merchant: "Crypto Signals Pro",
    score: 91,
    severity: "Critical",
    owner: "Dinda",
    age: "42m",
  },
  {
    id: "RSK-4804",
    subject: "Bank account name mismatch",
    merchant: "Template Cerdas",
    score: 67,
    severity: "Medium",
    owner: "Raka",
    age: "3h",
  },
  {
    id: "RSK-4791",
    subject: "Rapid withdrawal after settlement",
    merchant: "Preset Nusantara",
    score: 58,
    severity: "Medium",
    owner: "Dinda",
    age: "8h",
  },
];

export const auditEvents = [
  {
    id: "evt_91KM",
    actor: "admin@fersaku.id",
    action: "withdrawal.approved",
    target: "WD-120724-0089",
    ip: "103.28.54.11",
    result: "Success",
    time: "2 menit lalu",
  },
  {
    id: "evt_91KJ",
    actor: "system",
    action: "payment.marked_paid",
    target: "qris_2Yc91p",
    ip: "internal",
    result: "Success",
    time: "4 menit lalu",
  },
  {
    id: "evt_91KF",
    actor: "dinda@fersaku.id",
    action: "merchant.restricted",
    target: "str_01H8D1",
    ip: "36.85.22.194",
    result: "Success",
    time: "21 menit lalu",
  },
  {
    id: "evt_91KA",
    actor: "asep@ai.tools",
    action: "api_key.created",
    target: "key_7b2f",
    ip: "180.252.91.4",
    result: "Success",
    time: "37 menit lalu",
  },
  {
    id: "evt_919X",
    actor: "unknown",
    action: "admin.login_failed",
    target: "admin@fersaku.id",
    ip: "45.61.184.21",
    result: "Blocked",
    time: "1 jam lalu",
  },
];

export const platformVolume = [
  38, 42, 37, 52, 48, 63, 59, 71, 67, 81, 76, 92, 84, 97, 89, 100, 94, 108, 102,
  116, 109, 124, 118, 132,
];

export const adminRoles = [
  {
    id: "role_superadmin",
    name: "Super administrator",
    description:
      "Unrestricted platform access including roles, secrets, and emergency controls.",
    members: 2,
    system: true,
    color: "#5b7cfa",
  },
  {
    id: "role_finance",
    name: "Finance operations",
    description:
      "Payments, reconciliation, balance adjustments, and withdrawal approval.",
    members: 3,
    system: false,
    color: "#28a566",
  },
  {
    id: "role_risk",
    name: "Risk analyst",
    description:
      "Merchant review, cases, restrictions, evidence, and payout holds.",
    members: 4,
    system: false,
    color: "#e59633",
  },
  {
    id: "role_support",
    name: "Customer support",
    description:
      "Read merchants and orders, resend delivery, and manage support notes.",
    members: 7,
    system: false,
    color: "#9a6de2",
  },
  {
    id: "role_auditor",
    name: "Read-only auditor",
    description: "Read access to platform records and immutable audit events.",
    members: 2,
    system: false,
    color: "#738099",
  },
];

export const permissionGroups = [
  {
    group: "Merchants",
    permissions: [
      ["merchants.read", "View merchant profiles and balances"],
      ["merchants.update", "Edit verification and settlement settings"],
      ["merchants.restrict", "Restrict, suspend, or restore merchants"],
      ["merchants.impersonate", "Open seller dashboard as merchant"],
    ],
  },
  {
    group: "Money movement",
    permissions: [
      ["orders.refund", "Issue full or partial refunds"],
      ["payments.reconcile", "Run provider reconciliation"],
      ["balance.adjust", "Create manual balance adjustments"],
      ["withdrawals.review", "Review withdrawal evidence"],
      ["withdrawals.approve", "Approve and execute disbursements"],
    ],
  },
  {
    group: "Risk & trust",
    permissions: [
      ["risk.read", "View signals and investigations"],
      ["risk.manage", "Assign and resolve risk cases"],
      ["funds.hold", "Place merchant funds on hold"],
      ["webhooks.retry", "Retry platform or seller webhooks"],
    ],
  },
  {
    group: "Platform",
    permissions: [
      ["providers.read", "View provider health and routing"],
      ["providers.manage", "Change provider routing or test credentials"],
      ["settings.manage", "Change fees, settlement, limits, and flags"],
      ["roles.manage", "Create roles and assign permissions"],
      ["audit.export", "Export immutable audit data"],
      ["maintenance.manage", "Enable emergency maintenance mode"],
    ],
  },
];
