export const securityEvents = [
  [
    "SEC-9218",
    "Impossible travel detected",
    "admin@fersaku.id",
    "Jakarta → Frankfurt in 21m",
    "High",
    "Investigating",
    "2m",
  ],
  [
    "SEC-9212",
    "API secret viewed",
    "dinda@fersaku.id",
    "Email provider token",
    "Medium",
    "Verified",
    "18m",
  ],
  [
    "SEC-9198",
    "Repeated MFA failure",
    "unknown",
    "admin login • 45.61.184.21",
    "High",
    "Blocked",
    "1h",
  ],
  [
    "SEC-9181",
    "New trusted device",
    "finance@fersaku.id",
    "Chrome • macOS • Bandung",
    "Low",
    "Verified",
    "3h",
  ],
  [
    "SEC-9174",
    "Role permission changed",
    "superadmin@fersaku.id",
    "Finance operations + providers.read",
    "Medium",
    "Reviewed",
    "6h",
  ],
  [
    "SEC-9169",
    "Merchant impersonation",
    "support@fersaku.id",
    "Asep AI Tools • read-only",
    "Medium",
    "Ended",
    "8h",
  ],
];
