import type { BuilderConfig, StorefrontTemplate } from "./types";

export const storefrontTemplates: StorefrontTemplate[] = [
  {
    name: "Atelier",
    note: "Editorial creator store",
    colors: ["#173f2c", "#d7ff64", "#f4f2eb"],
    config: {
      accent: "#d7ff64",
      ink: "#173f2c",
      canvas: "#f4f2eb",
      layout: "grid",
      hero: "statement",
      cards: "soft",
      texture: "noise",
      radius: "round",
      font: "editorial",
      align: "left",
    },
  },
  {
    name: "Signal",
    note: "Bold launch energy",
    colors: ["#121a31", "#ff7958", "#eef3ff"],
    config: {
      accent: "#ff7958",
      ink: "#121a31",
      canvas: "#eef3ff",
      layout: "editorial",
      hero: "spotlight",
      cards: "poster",
      texture: "grid",
      radius: "soft",
      font: "modern",
      align: "left",
    },
  },
  {
    name: "Paper",
    note: "Warm design studio",
    colors: ["#1d2433", "#ffd75a", "#f7f1e8"],
    config: {
      accent: "#ffd75a",
      ink: "#1d2433",
      canvas: "#f7f1e8",
      layout: "editorial",
      hero: "split",
      cards: "outline",
      texture: "grid",
      radius: "soft",
      font: "editorial",
      align: "center",
    },
  },
  {
    name: "Mono",
    note: "Developer-first catalog",
    colors: ["#111111", "#a8ff78", "#f1f1ed"],
    config: {
      accent: "#a8ff78",
      ink: "#111111",
      canvas: "#f1f1ed",
      layout: "catalog",
      hero: "compact",
      cards: "compact",
      texture: "clean",
      radius: "sharp",
      font: "mono",
      align: "left",
      density: "compact",
    },
  },
  {
    name: "Sunday",
    note: "Friendly personal shop",
    colors: ["#43362d", "#ffb8ca", "#fff7e8"],
    config: {
      accent: "#ffb8ca",
      ink: "#43362d",
      canvas: "#fff7e8",
      layout: "grid",
      hero: "split",
      cards: "soft",
      texture: "dots",
      radius: "round",
      font: "friendly",
      align: "center",
    },
  },
  {
    name: "Gallery",
    note: "Art-forward product showcase",
    colors: ["#252019", "#94c8ff", "#f4efe7"],
    config: {
      accent: "#94c8ff",
      ink: "#252019",
      canvas: "#f4efe7",
      layout: "minimal",
      hero: "spotlight",
      cards: "poster",
      texture: "clean",
      radius: "soft",
      font: "editorial",
      align: "left",
    },
  },
  {
    name: "Commerce",
    note: "Dense high-volume catalog",
    colors: ["#102b39", "#53e0bd", "#edf7f4"],
    config: {
      accent: "#53e0bd",
      ink: "#102b39",
      canvas: "#edf7f4",
      layout: "catalog",
      hero: "compact",
      cards: "compact",
      texture: "grid",
      radius: "soft",
      font: "modern",
      align: "left",
      density: "compact",
    },
  },
  {
    name: "Nocturne",
    note: "Premium dark storefront",
    colors: ["#f5efe4", "#ffcf70", "#111513"],
    config: {
      accent: "#ffcf70",
      ink: "#f5efe4",
      canvas: "#111513",
      layout: "editorial",
      hero: "statement",
      cards: "outline",
      texture: "noise",
      radius: "round",
      font: "editorial",
      align: "center",
    },
  },
];

export const initialStorefrontConfig: BuilderConfig = {
  template: "Atelier",
  name: "Asep AI Tools",
  tagline: "Kerja lebih singkat. Hasil lebih tajam.",
  bio: "Tools, template, dan workflow praktis untuk membantumu bekerja lebih cerdas dengan AI.",
  announcement: "Gratis pembaruan AI Prompt Pack v3 untuk semua pembeli lama",
  announcementEnabled: true,
  accent: "#d7ff64",
  ink: "#173f2c",
  canvas: "#f4f2eb",
  layout: "grid",
  hero: "statement",
  cards: "soft",
  texture: "noise",
  radius: "round",
  font: "editorial",
  align: "left",
  density: "comfortable",
  showSearch: true,
  showSales: true,
  showRatings: true,
  featuredIds: ["prod_01", "prod_03"],
  sections: [
    { id: "featured", label: "Produk unggulan", visible: true },
    { id: "products", label: "Semua produk", visible: true },
    { id: "reviews", label: "Ulasan pembeli", visible: true },
    { id: "trust", label: "Trust badges", visible: true },
    { id: "about", label: "Tentang toko", visible: true },
    { id: "newsletter", label: "Newsletter", visible: false },
  ],
  trustBadges: ["Pembayaran QRIS aman", "Akses instan", "Lifetime access"],
  instagram: "@asep.ai",
  website: "https://asep.ai",
  customLinks: [{ label: "Free resources", url: "https://asep.ai/free" }],
  seoTitle: "Asep AI Tools — AI Templates & Workflows",
  seoDescription:
    "Template dan workflow AI berbahasa Indonesia untuk kreator dan builder.",
};
