export const posts = [
  {
    slug: "checkout-qris-conversion",
    title: "Mendesain checkout QRIS yang tidak membunuh conversion",
    category: "Product",
    date: "10 Jul 2026",
    read: "7 min",
    color: "#d7ff64",
  },
  {
    slug: "harga-produk-digital",
    title: "Cara menentukan harga produk digital tanpa menebak",
    category: "Creator guide",
    date: "4 Jul 2026",
    read: "9 min",
    color: "#ffb69d",
  },
  {
    slug: "delivery-otomatis",
    title: "Mengapa delivery otomatis membangun kepercayaan pembeli",
    category: "Commerce",
    date: "28 Jun 2026",
    read: "5 min",
    color: "#c9defd",
  },
  {
    slug: "qris-api-builder",
    title: "QRIS API untuk builder Indonesia: konsep dan pola integrasi",
    category: "Engineering",
    date: "20 Jun 2026",
    read: "11 min",
    color: "#d5c8ff",
  },
  {
    slug: "ledger-saldo-seller",
    title: "Di balik saldo seller: ledger, settlement, dan payout",
    category: "Engineering",
    date: "12 Jun 2026",
    read: "8 min",
    color: "#bdf8d0",
  },
  {
    slug: "toko-digital-pertama",
    title: "Meluncurkan toko digital pertamamu dalam satu sore",
    category: "Creator guide",
    date: "2 Jun 2026",
    read: "6 min",
    color: "#ffe69a",
  },
];
