export const reviews = [
  {
    id: "rev_01",
    productId: "prod_01",
    product: "AI Prompt Pack",
    seller: "Asep AI Tools",
    buyer: "Nadia Putri",
    initials: "NP",
    rating: 5,
    title: "Langsung kepakai untuk kerja",
    body: "Prompt-nya tidak generik dan struktur Notion-nya rapi. Dalam dua hari sudah kepakai untuk riset konten dan brief client.",
    verified: true,
    status: "Published",
    createdAt: "12 Jul 2026",
    sellerReply:
      "Terima kasih, Nadia! Senang sekali pack-nya langsung berguna. Update v3.1 juga sudah tersedia di buyer portal.",
  },
  {
    id: "rev_02",
    productId: "prod_01",
    product: "AI Prompt Pack",
    seller: "Asep AI Tools",
    buyer: "Rizky Hidayat",
    initials: "RH",
    rating: 4,
    title: "Bagus dan mudah dimodifikasi",
    body: "Contohnya relevan untuk Bahasa Indonesia. Akan lebih bagus kalau ada lebih banyak prompt untuk sales.",
    verified: true,
    status: "Published",
    createdAt: "10 Jul 2026",
  },
  {
    id: "rev_03",
    productId: "prod_04",
    product: "Figma Landing Kit",
    seller: "DesignKit Studio",
    buyer: "Citra Ayu",
    initials: "CA",
    rating: 5,
    title: "Auto-layout-nya bersih",
    body: "Sangat mempercepat proses eksplorasi. Komponennya konsisten dan dokumentasinya jelas.",
    verified: true,
    status: "Published",
    createdAt: "8 Jul 2026",
  },
  {
    id: "rev_04",
    productId: "prod_account",
    product: "Canva Pro Team — 30 Hari",
    seller: "Digital Supply ID",
    buyer: "Anonim",
    initials: "A",
    rating: 2,
    title: "Perlu instruksi lebih jelas",
    body: "Akun bisa dipakai tetapi saya sempat bingung dengan team link yang diberikan.",
    verified: true,
    status: "Pending moderation",
    createdAt: "12 Jul 2026",
  },
];

export const ratingSummary = {
  average: 4.8,
  total: 186,
  distribution: { 5: 154, 4: 23, 3: 6, 2: 2, 1: 1 },
};
